hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from reserve import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('reserve.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# app_name = 'home'
# urlpatterns = [
#   path('', views.home, name='home'),
#   path('about-us/', views.about, name='about'),
#      path('account/', include('account.urls')),
# ]

reserve/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from reserve import views


app_name = 'reserve'
urlpatterns = [
    path('', views.available_rooms, name='available_rooms'),
    path('reserve-room/<int:pk>/', views.reserve_room, name='reserve_room'),
    # path('about-us/', views.about, name='about'),
]

reserve/models.py
from django.db import models


# Create your models here.
class Room(models.Model):
    # Integer
    ROOM_OPTIONS = (
        ('Executive', 'Executive Room'),
        ('Standard', 'Standard Room'),
        ('Villa', 'Villa Room'),
        ('Double', 'Double Room'),
    )
    room_number = models.IntegerField()
    availability = models.BooleanField(default=True)
    room_type = models.CharField(max_length=200, choices=ROOM_OPTIONS)
    price = models.IntegerField()
#  Need edit Picture
    room_picture = models.ImageField(upload_to='uploads/', height_field=None, width_field=None, max_length=100)

    
    def __str__(self):
        return str(self.room_number) + self.room_type

class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='reservations')
    date_from = models.DateField()
    date_to = models.DateField()
    days = models.IntegerField(default=1)
    total_price = models.IntegerField()
    room_type = models.CharField(max_length=200)
    customer_name = models.CharField(max_length=200)
    customer_email = models.CharField(max_length=200)
    customer_number = models.CharField(max_length=200)

    def __str__(self):
        return self.customer_name + "\'s reservation"

reserve/forms.py
from datetime import date
from django.forms import Form, ModelForm, DateField, widgets
from django import forms
from .models import Reservation

today = date.today()

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('customer_name', 'customer_email', 'customer_number', 'date_from', 'date_to', 'days')
        # date_from = forms.DateField(widget=forms.DateInput(attrs={'min': today, 'value': today, 'type': 'date'}), required=True)

        widgets = {
            'date_from': widgets.DateInput(attrs={'type': 'date', 'value': today}),
            'date_to': widgets.DateInput(attrs={'type': 'date'}),
        }

reserve/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Room
from .forms import ReservationForm
from django.contrib import messages


# Create your views here.
def available_rooms(request):
    available_rooms = Room.objects.filter(availability = True)
    
    return render(request, 'reserve/available_rooms.html', {'available_rooms':available_rooms})

def reserve_room(request, pk):
  room = get_object_or_404(Room, pk=pk)
  if request.method == "POST":
    reservation_form = ReservationForm(request.POST)
    if reservation_form.is_valid():
        new_reservation = reservation_form.save(commit=False)
        # if room.availability = False:
        #       return render(request, 'reserve/reserve_success.html', {'reservation_code': reservation_code})

        new_reservation.room = room
        new_reservation.room_type = room.room_type
        new_reservation.total_price = new_reservation.days * room.price
        new_reservation.save()
        # reservation_form.save()
        reservation_code = new_reservation.pk
        room.availability = False
        room.price = 300
        room.save()
        return render(request, 'reserve/reserve_success.html', {'reservation_code': reservation_code})
    else:
        messages.error(request, 'Error MAKING RESERVATION, TRY AGAIN')

    # SOMETHING VBETTER FOR THIS REDIRECT
    return redirect("reserve:available_rooms")

  form = ReservationForm()
  return render(request, 'reserve/reserve_room.html', {'room':room, 'form': form})
	# return render(request=request, template_name="main/home.html", context={'movie_form':movie_form, 'movies':movies})

reserve/templates/reserve/available_rooms.html
{% extends 'reserve/base.html' %}
{% load static %}

<!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->

{% block content %}
    <!-- <h3>hi</h3>
    {% for room in available_rooms %}
    <h3>Room Number{{ room.room_number }} - Type {{ room.room_type }} </h3>
    <h4>Availability: {% if room.availability == True %}Available {% else %} Not Available {% endif %} </h4>
    <img src="{{ room.room_picture.url }}" class="responsive-img" style='height:250px; width:300px'>
    WORKING -->
    <!-- <button>Book Room</button>
    <a class="blue-text text-lighten-1" href="{% url 'reserve:reserve_room' room.pk %}">Book Room</a>
     {% endfor %} -->

 <!--  -->
        <h4 class="center" style="padding: 50px 0;">Available Rooms:</h4>

        <div>
          <div class="row">
            {% for room in available_rooms %}
            <div class="col s12 m4 l3">
          <div class="card center">
            <div class="card-image"> 
              <img src="{{ room.room_picture.url }}" class="responsive-img" style='height:250px; width:300px'>
              <span class="card-title blue" style='padding:0'> Standard Room </span>
            </div>
           <div class="card-content" style='padding: 10px'>
              <div style='padding: 15px'>                
                <h6 class="card-title">N40,000</h6>
                  <!-- <h6>  property.area}}, property.state}} </h6> -->
                  <h6>Room Number: {{ room.room_number }}</h6>
                  <button class="btn blue lighten-2" style="width:100%"><a class="white-text" href="{% url 'reserve:reserve_room' room.pk %}">Reserve Room</a></button>

                  <!-- <p class="grey-text"> property.full_desc}}</p> -->
              </div>
                
              
        
            </div>
          </div>
        </div>
        {% empty %}
        <h4>All our rooms have been booked at the moment, kindly come back later</h4>
        {% endfor %}
        
        </div>
        </div>
<!--  -->



{% endblock %}    
</body>
</html>


<!-- AGENT -->
    <!-- <div class="row"> -->
        <!-- <div class="col s12 m4 l3">
        <div class="card-panel small">
          <div class="card-image"> 
            <img src="{{ room.room_picture.url }}" class="responsive-img" style='height:250px; width:300px'>
          </div>
         <div class="card-content">
            <h5 class="card-title">
            <a class="blue-text text-lighten-2" href=" url 'artisans:detail_view' artisan.state artisan.slug artisan.pk "> artisan.company}}</a></h5>
            <h6><i class="material-icons blue-text text-lighten-2">place</i> artisan.address}},  artisan.state}} </h6>
            <h6 class="chip"> artisan.services}}</h6>
          </div>
        </div>
      </div> -->

reserve/templates/reserve/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'reserve/css/materialize.min.css' %}" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href='{% static "reserve/css/style.css" %}'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="blue lighten-1">
        <div class="container">
          <div class="nav-wrapper">
            <a href="/" class="brand-logo">Kano Hotel</a>
            <a href="#" class="button-collapse" data-activates="mobile-nav"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="/" style="font-size: 18px">Home</a></li>
                <li><a href="/" style="font-size: 18px" class="btn white blue-text waves-effect waves-teal">RESERVE</a></li>
                <li><a class="btn white blue-text waves-effect waves-teal" href="/admin/" style="font-size: 18px">Manager Login</a></li>
            </ul>
            <ul id="mobile-nav" class="side-nav">
              <li><a href="/" class="btn white blue-text text-lighten-2" style="font-size: 18px">Home</a></li>
              <li><a href="/" class="btn white blue-text text-lighten-2" style="font-size: 18px">About Us</a></li>
              <li><a href="/" style="font-size: 18px" class="dropdown-button" data-activates='services-m'>Services</a></li>
              <li><a href="/" class="btn white blue-text text-lighten-2" style="font-size: 18px">Contact Us</a></li>
              <li><a href="/" style="font-size: 18px" class="btn blue white-text waves-effect waves-teal">RESERVE</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- <ul id="services" class="dropdown-content center">
        <li><a class="blue-text text-lighten-1" href="/materials" style="font-size: 18px">Building Materials</a></li>      
        <li><a class="blue-text text-lighten-1" href="/estate" style="font-size: 18px">Estate</a></li>
        <li><a class="blue-text text-lighten-1" href="/artisans" style="font-size: 18px">Artisans</a></li>
      </ul> -->
      <!-- MOBILE DORPDOWN -->
      <!-- <ul id="services-m" class="dropdown-content center">
        <li><a class="blue-text text-lighten-1" href="/materials" style="font-size: 18px">Building Materials</a></li>      
        <li><a class="blue-text text-lighten-1" href="/estate" style="font-size: 18px">Estate</a></li>
        <li><a class="blue-text text-lighten-1" href="/artisans" style="font-size: 18px">Artisans</a></li>
      </ul> -->
    {% block content %}
    {% endblock %}

    <footer class="page-footer blue lighten-1">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">About Us</h5>
              <p class="grey-text text-lighten-4">
                With a wide range of services catered to both business and leisure travelers, Kano Hotel makes sure you get the best out of your stay.
              </p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text"><a class="white-text text-lighten-3" href="/admin/" style="font-size: 18px">Manager Login</a></h5>
            </div>
          </div>
        </div>
        <div class="footer-copyright">
          <div class="container" style="font-weight:500; font-size:22px">
            Copyright 2020
            <a href="#" class="grey-text text-lighten-4 right">Kano Hotel</a>
          </div>
        </div>
      </footer>

    <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="{% static 'home/js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'home/js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'home/js/test.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('.dropdown-button').dropdown({
        constrainWidth: false,
        hover: true,
        belowOrigin: true,
        alignment: 'left'
      });

      // JAVASCRIPT START HERE //
      //Activate Slider
      $('.slider').slider({
        height: '70vh',
        indicators: false,
        interval: 3000,
      });
      $('.button-collapse').sideNav();
      $('select').material_select();
      $('.dropdown-button')      
    });
  </script>
</body>

reserve/templates/reserve/reserve_room.html
{% extends 'reserve/base.html' %}
{% load static %}

{% block content %}

<div class="row center" style="padding: 20px;">
  <h3>Book Room: {{ room.room_number }} - Type: {{ room.type }}</h3>
  <form method="post" enctype="multipart/form-data">
    {{ form }}
    {% csrf_token %}
    <button class="btn btn-primary my-4" type="submit">Reserve</button>
  </form>
</div>

{% endblock %}

reserve/templates/reserve/reserve_success.html
{% extends 'reserve/base.html' %}
{% load static %}

<!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->

{% block content %}
<div class="row center">
    <div style="padding: 40px;">
        <h5>You have successfully made your reservation: Reservation code is: <br> <h3>{{ reservation_code }}  </h3>
            Kindly take a screenshot of it to save and show at our front desk.</h5>

            <button class="btn blue lighten-2" style="width:100%"><a class="white-text" href="{% url 'reserve:available_rooms' %}">Reserve Another Room</a></button>

    </div>
</div>    
{% endblock %}    
</body>
</html>